#!/usr/bin/env bash
# Configure your Nginx server so that `/redirect_me` is redirecting to another page.

# Requirements:
#     The redirection must be a “301 Moved Permanently”
#     You answer file should be a Bash script containing commands to automatically configure
#         a Ubuntu machine to respect above requirements
#     Using what you did with `1-install_nginx_web_server`, write `3-redirection` so that it configures a
#         brand new Ubuntu machine to the requirements asked in this task

CONFIG_FILE="/etc/nginx/sites-available/default"
# install nginx
apt-get -y update
apt-get -y install nginx

# update index.html file
echo 'Hello World!' > /usr/share/nginx/html/index.html

# update config file to redirect
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://google.com/;
    }
}" > $CONFIG_FILE

# start nginx after reloading config
service nginx start
