#!/usr/bin/env bash
# Configure your Nginx server so that `/redirect_me` is redirecting to another page.

# Requirements:
# The redirection must be a “301 Moved Permanently”
# You answer file should be a Bash script containing commands to automatically configure
# a Ubuntu machine to respect above requirements
# Using what you did with `1-install_nginx_web_server`, write `3-redirection` so that it configures a
# brand new Ubuntu machine to the requirements asked in this task

sudo apt-get update -y
sudo apt-get install -y nginx
sudo chmod -R 777 /var/www
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
# New Addition
replace="listen \[::\]:80 default_server;"
replacement="listen \[::\]:80 default_server;\n\tlocation \/redirect_me {rewrite \/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent; return 301;}"
file="/etc/nginx/sites-available/default"
sudo sed -i s/"$replace"/"$replacement"/g "$file"
sudo service nginx restart
