#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains 
#     the string `Ceci n'est pas une page`.

# Requirements:
#     The page must return an HTTP 404 error code
#     The page must contain the string `Ceci n'est pas une page`
#     Using what you did with `3-redirection`, write `4-not_found_page_404` so that it configures a brand
#         new Ubuntu machine to the requirements asked in this task

CONFIG_FILE="/etc/nginx/sites-available/default"
# install nginx
apt-get -y update
apt-get -y install nginx

# update index.html file
echo 'Holberton School' > /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# update config file to redirect
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://google.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /usr/share/nginx/html;
      internal;
    }
}" > $CONFIG_FILE

# start nginx after reloading config
service nginx start
