#!/usr/bin/env bash
#Using your debugging skills, find out what is keeping your Ubuntu container is Nginx installation from
#listening on port 80. Feel free to install whatever tool you need, start and destroy as many containers as
#you need to debug the issue. Then, write a Bash script with the minimum number of commands to automate your #fix.

#Requirements:

#Nginx must be running, and listening on port 80 of all the server's active IPv4 IPs
#Write a Bash script that configures a server to the above requirements

# adjust nginx config ports 8080 with port 80
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
# start nginx service on the adjusted port
service nginx start
