#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes
# Displays hours from 0 to 12
# Displays minutes from 1 to 59
# uses the while loop

hr=0
mins=1
while [ $hr -le 12 ]
    do
        echo "Hour: $hr"
        while [ $mins -le 59 ]
            do
                echo "$mins"
                (( mins++ ))
            done
        (( hr++ ))
    done
