#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash

dir_items=$(ls)

for item in $dir_items
    do
        echo "$item" | cut -d '-' -f 2-
    done
