#!/usr/bin/env bash
# Get `Apache` running on the container and return a page
# that contains`Hello Holberton` when querying the root of it.

sudo apt update -y
sudo apt install -y apache2
echo "Hello Holberton" > /var/www/html/index.html
sudo systemctl enable apache2
sudo service apache2 start
