#!/usr/bin/env bash
# Requirements:
# `nginx` must be running as `nginx` user
# `nginx` must be listening on all active IPs on port `8080`
# You cannot use `apt-get remove`
# Write a Bash script that configures the container to fit the above requirements

sed -i 's/80 default_server/8080 default_server/g' '/etc/nginx/sites-available/default'
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
