#!/usr/bin/env bash
# Write a Bash script that uses `ssh` to connect to your server using the private key `~/.ssh/school` with the user `ubuntu`.

# Requirements:
#     Only use `ssh` single-character flags
#     You cannot use `-l`
#     You do not need to handle the case of a private key protected by a passphrase

# Define variables
server_ip="3.86.13.200"
private_key="~/.ssh/school"
user="ubuntu"

# SSH connection with single-character flags
#ssh -i "$private_key" "$user"@"$server_ip"

ssh -i ~/.ssh/school ubuntu@3.238.87.140
